<?xml version="1.0" encoding="utf-8"?><Database Name="PTUD" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=DESKTOP-2UM47P3;Initial Catalog=PTUD;Integrated Security=True" SettingsObjectName="WindowsFormsApplication1.Properties.Settings" SettingsPropertyName="PTUDConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.NV" Member="NVs">
    <Type Name="NV">
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="userAccount" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="userPassword" Type="System.String" DbType="NVarChar(18) NOT NULL" CanBeNull="false" />
      <Column Name="userEmail" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="userPhone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="role" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="activation" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="NV_OrderTable" Member="OrderTables" ThisKey="userID" OtherKey="userID" Type="OrderTable" />
    </Type>
  </Table>
  <Table Name="dbo.VendorProduct" Member="VendorProducts">
    <Type Name="VendorProduct">
      <Column Name="VendorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Association Name="Product_VendorProduct" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
      <Association Name="Vendor_VendorProduct" Member="Vendor" ThisKey="VendorID" OtherKey="VendorID" Type="Vendor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderDetail" Member="OrderDetails">
    <Type Name="OrderDetail">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orderDetailID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="orderID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="tax" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="orderQuantity" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="OrderTable_OrderDetail" Member="OrderTable" ThisKey="orderID" OtherKey="orderID" Type="OrderTable" IsForeignKey="true" />
      <Association Name="Product_OrderDetail" Member="Product" ThisKey="ProductID" OtherKey="ProductID" Type="Product" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.OrderTable" Member="OrderTables">
    <Type Name="OrderTable">
      <Column Name="orderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="userID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="status" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="orderDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="modifyDate" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="modifyUser" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="VendorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="OrderTable_OrderDetail" Member="OrderDetails" ThisKey="orderID" OtherKey="orderID" Type="OrderDetail" />
      <Association Name="NV_OrderTable" Member="NV" ThisKey="userID" OtherKey="userID" Type="NV" IsForeignKey="true" />
      <Association Name="Vendor_OrderTable" Member="Vendor" ThisKey="VendorID" OtherKey="VendorID" Type="Vendor" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Product" Member="Products">
    <Type Name="Product">
      <Column Name="ProductID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="ProductType" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="ProductCategoryID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ProductPrice" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Manufacture" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Association Name="Product_VendorProduct" Member="VendorProducts" ThisKey="ProductID" OtherKey="ProductID" Type="VendorProduct" />
      <Association Name="Product_OrderDetail" Member="OrderDetails" ThisKey="ProductID" OtherKey="ProductID" Type="OrderDetail" />
      <Association Name="ProductCategory_Product" Member="ProductCategory" ThisKey="ProductCategoryID" OtherKey="ProductCategoryID" Type="ProductCategory" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ProductCategory" Member="ProductCategories">
    <Type Name="ProductCategory">
      <Column Name="ProductCategoryID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ProductCategoryName" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
      <Association Name="ProductCategory_Product" Member="Products" ThisKey="ProductCategoryID" OtherKey="ProductCategoryID" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Vendor" Member="Vendors">
    <Type Name="Vendor">
      <Column Name="VendorID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="VendorName" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="VendorAddress" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="VAT" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="VendorEmail" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="VendorPhone" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="VendorAvailable" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Association Name="Vendor_VendorProduct" Member="VendorProducts" ThisKey="VendorID" OtherKey="VendorID" Type="VendorProduct" />
      <Association Name="Vendor_OrderTable" Member="OrderTables" ThisKey="VendorID" OtherKey="VendorID" Type="OrderTable" />
    </Type>
  </Table>
</Database>